name: Deploy Serene Zola site to Pages
on:
  push:
    branches:
      - main  # or 'master' depending on your default branch name

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive' # Important for fetching the Serene theme

      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.21.0 # Match this to your local Zola version
        env:
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}